version: '3.8'

services:
  # MySQL database
  mysql-db:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'admin@123'
      MYSQL_DATABASE: 'nadsoft'
      MYSQL_PASSWORD: 'admin@123'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
